"""The cull. Chris reads passages and says keep or pass.

Every verdict appends to `extracted/decisions.jsonl` and nothing is ever
overwritten, because the decisions are the training data. A pass is as
informative as a keep — arguably more so, since the pool is mostly passes and
a discriminator needs negatives.

Keys: k keep, p pass, m maybe, s skip (no verdict recorded), b back, q quit.
Anything typed after the letter is kept as a note on that verdict.
"""

from __future__ import annotations

import random
import textwrap
from pathlib import Path

from .bank import Bank

WRAP = 96


def _render(p: dict, i: int, total: int) -> str:
    head = (
        f"[{i}/{total}]  {p.get('title', '?')}"
        f"{'  — ' + p['author'] if p.get('author') else ''}"
    )
    meta = (
        f"score {p.get('score', 0):.3f}   {p.get('words', 0)}w   "
        f"pos {p.get('position', 0):.2f}   {p.get('source_id', '')}"
    )
    tags = "  ".join(f"[{t}]" for t in p.get("tags", [])) or "[untagged]"
    body = "\n".join(
        textwrap.fill(para, WRAP) for para in p.get("text", "").split("\n\n")
    )
    rule = "─" * WRAP
    return f"\n{rule}\n{head}\n{meta}\n{tags}\n{rule}\n\n{body}\n\n{rule}"


def review(
    root: str | Path = ".",
    out: str | Path | None = None,
    tag: str | None = None,
    order: str = "score",
    limit: int = 0,
    min_score: float = 0.0,
) -> None:
    bank = Bank(out or Path(root) / "extracted")
    pool = bank.load()
    done = bank.verdicts()

    queue = [p for pid, p in pool.items() if pid not in done]
    if tag:
        queue = [p for p in queue if tag in (p.get("tags") or [])]
    queue = [p for p in queue if p.get("score", 0) >= min_score]

    if order == "score":
        queue.sort(key=lambda p: -p.get("score", 0))
    elif order == "random":
        random.shuffle(queue)
    elif order == "source":
        queue.sort(key=lambda p: (p.get("source_id", ""), -p.get("score", 0)))
    if limit:
        queue = queue[:limit]

    if not queue:
        print("Nothing unlabelled matches. `pipeline stats` for the state of the bank.")
        return

    print(f"{len(queue)} to review.  k=keep  p=pass  m=maybe  s=skip  b=back  q=quit")
    i = 0
    while 0 <= i < len(queue):
        p = queue[i]
        print(_render(p, i + 1, len(queue)))
        try:
            ans = input("> ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            print("\nstopped.")
            break
        if ans in ("q", "quit"):
            break
        if ans in ("b", "back"):
            i = max(0, i - 1)
            continue
        if ans in ("s", "skip", ""):
            i += 1
            continue
        verdict = {"k": "keep", "p": "pass", "m": "maybe"}.get(ans[:1])
        if not verdict:
            print("  ? k / p / m / s / b / q")
            continue
        note = ans[1:].strip()
        bank.record(p["id"], verdict, note=note)
        i += 1

    s = bank.stats()
    print(f"\nkeep {s['keep']}  pass {s['pass']}  maybe {s['maybe']}  "
          f"unlabelled {s['unlabelled']}  of {s['pool']}")


def export(root: str | Path = ".", out: str | Path | None = None,
           path: str | Path | None = None) -> Path:
    """Write the kept set to `extracted/exemplars.md` in the documented format."""
    out_dir = Path(out or Path(root) / "extracted")
    bank = Bank(out_dir)
    kept = sorted(bank.kept(), key=lambda p: (p.get("tags") or ["zz"])[0])
    dest = Path(path) if path else out_dir / "exemplars.md"

    lines = [
        "# EXEMPLARS — register conditioning",
        "",
        "*Generated by `pipeline export`. Chris's keeps from "
        "`exemplars.jsonl`; do not hand-edit — edit the decisions instead.*",
        "",
        f"{len(kept)} passages.",
        "",
    ]
    for p in kept:
        src = p.get("title", "?")
        who = p.get("author") or p.get("source_id", "")
        tags = " ".join(f"`[{t}]`" for t in p.get("tags", [])) or "`[untagged]`"
        lines += [f"### {who} — {src}", tags, "", p.get("text", ""), ""]
        if p.get("license"):
            lines += [f"<!-- {p['license']}; {p.get('origin','')} -->", ""]
    dest.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {dest} ({len(kept)} passages)")
    return dest
